export * from "@/lib/storage/file-storage";
export {
    createPendingAttachment,
    savePendingAttachment,
    saveAttachments,
    loadAttachmentData,
    getAttachmentDataUri,
    deleteAttachmentWithFile,
    deleteAttachmentsByMessage,
    cleanupOrphanedFiles as cleanupAttachmentOrphanedFiles,
    getImageStorageUsage,
    getAttachment,
    getAttachmentsByMessage,
    type PendingAttachment,
} from "@/lib/storage/attachment-storage";
export {
    getApiKey,
    setApiKey,
    clearApiKey,
    getAuthToken,
    setAuthToken,
    clearAuthToken,
    getRefreshToken,
    setRefreshToken,
    clearRefreshToken,
    clearAllCredentials,
} from "@/lib/storage/credential-storage";
export {
    getSyncState,
    setSyncState,
    clearSyncState,
    getSyncMetadata,
    setSyncMetadata,
    updateSyncMetadata,
    getTheme,
    setTheme,
    getHasCompletedOnboarding,
    setHasCompletedOnboarding,
    getCloudDefaultSkillId,
    setCloudDefaultSkillId,
    getCloudSelectedSkillId,
    setCloudSelectedSkillId,
    getCloudSelectedSkillMode,
    setCloudSelectedSkillMode,
    type UserTheme,
} from "@/lib/storage/sync-storage";
export {
    getDefaultThinking,
    setDefaultThinking,
    getDefaultSearchLevel,
    setDefaultSearchLevel,
    getDefaultModel,
    setDefaultModel,
    getFavoriteModels,
    setFavoriteModels,
} from "@/lib/storage/user-settings-storage";
export {
    processImage,
    isValidImageMimeType,
    getMimeTypeFromUri,
    type ImageProcessingResult,
} from "@/lib/storage/image-processing";
export {
    getLocalQuotaStatus,
    getLocalQuotaUsageString,
    checkQuotaBeforeUpload,
    getStorageUsage,
    formatBytes,
    LOCAL_IMAGE_QUOTA,
    type QuotaStatus,
} from "@/lib/quota";
