import prettier from "prettier";

import type { DesiredGeneratedFiles, LocalManifest } from "./model.ts";

function renderDotEnvValue(value: string): string {
    return /^[A-Za-z0-9_./:@%+=,-]+$/.test(value)
        ? value
        : JSON.stringify(value);
}

function renderDotEnv(
    entries: Array<[string, string | null | undefined]>,
): string {
    const lines = [
        "# This file is generated by bun run bootstrap.",
        "# Manual edits are unsupported unless you adopt or force a rewrite through the wrapper workflow.",
        "",
    ];

    for (const [key, value] of entries) {
        if (value === null || value === undefined || value.length === 0) {
            continue;
        }
        lines.push(`${key}=${renderDotEnvValue(value)}`);
    }

    return `${lines.join("\n")}\n`;
}

export async function renderGeneratedFiles(params: {
    manifest: LocalManifest;
}): Promise<DesiredGeneratedFiles> {
    const { manifest } = params;
    const serverConfig = {
        ...manifest.serverConfig,
        stateId: manifest.stateId,
        sandboxRoot: manifest.sandboxRoot,
    };

    return {
        webEnv: renderDotEnv([
            ["PORT", String(manifest.webPort)],
            ["HOST", manifest.managedEnv.web.host],
            [
                "NEXT_PUBLIC_CONVEX_URL",
                manifest.managedEnv.web.nextPublicConvexUrl ??
                    manifest.convexCloudUrl,
            ],
            ["NEXT_PUBLIC_AGENTCHAT_SERVER_URL", manifest.serverUrl],
            [
                "NEXT_ALLOWED_DEV_ORIGINS",
                manifest.managedEnv.web.nextAllowedDevOrigins,
            ],
        ]),
        serverEnv: renderDotEnv([
            ["PORT", String(manifest.serverPort)],
            ["HOST", manifest.managedEnv.server.host],
            ["XDG_STATE_HOME", manifest.xdgStateHome],
            [
                "BACKEND_TOKEN_SECRET",
                manifest.managedEnv.server.backendTokenSecret,
            ],
            [
                "AGENTCHAT_CONVEX_SITE_URL",
                manifest.managedEnv.server.agentchatConvexSiteUrl,
            ],
            [
                "RUNTIME_INGRESS_SECRET",
                manifest.managedEnv.server.runtimeIngressSecret,
            ],
        ]),
        serverConfig: await prettier.format(
            JSON.stringify(serverConfig, null, 4),
            {
                filepath: manifest.generatedFiles.serverConfigPath,
                tabWidth: 4,
            },
        ),
    };
}
